// NOTE: [assembly: KSPAssembly("DearImGuiKSP", ...)] is generated by KSPBuildTools from the
// csproj <Version> — do not declare it here (duplicate attribute error).
// Version lockstep policy: managed and native DLLs release together; a mismatch at
// runtime trips the version-handshake failure mode (spec §5.4, D17).
