// NOTE: [assembly: KSPAssembly("DearKSPDemo", ...)] is generated by KSPBuildTools from
// the csproj <Version> — do not declare it here (duplicate attribute error).
//
// Hard dependency on Dear KSP (spec §10.5). EqualMajor is REQUIRED consumer guidance:
// KSP's loader treats any higher major as satisfying a plain KSPAssemblyDependency,
// which would let a breaking DearKSP 2.0 silently load under a consumer built for 0.x/1.x.
[assembly: KSPAssemblyDependencyEqualMajor("DearKSP", 0, 1)]
